name: 成都天气每日推送

on:
  schedule:
    # 每天早上8点执行一次 (UTC 0点 = 北京时间8点)
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  weather:
    runs-on: windows-latest
    environment: production

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: 缓存依赖
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 安装依赖
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        echo "正在安装项目依赖..."
        npm ci
        echo "✅ 依赖安装完成"

    - name: 推送天气信息
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
      run: |
        echo "开始推送成都青羊区天气信息..."
        node src/weather-daily.js

    - name: 执行结果
      if: always()
      run: |
        echo "天气推送任务执行完成"
        echo "时间: $(Get-Date)"